### ISSUE TITLE
Cannot edit file

### ISSUE THREAD

**Issue by wleibrook** [recoverysource-sites/hamilton#1]
I was goingclean up some things in the meeting.yaml file but when I click the edit button and hover over the "Edit File" it does not highlight and allow me to choose it. 
Also- the Noon meetings at  the 12 are showing 12 AM- they should show PM

**Comment by MTecknology** [comment]
I don't understand this description; a screenshot would be very helpful.

**Comment by wleibrook** [comment]
![no edit](https://github.com/recoverysource-sites/hamilton/assets/163310736/2c6a445e-e3ef-4651-bdfb-274fe8c882ef)

**Comment by wleibrook** [comment]
I think somehow it doesn't have me logged in properly let me check and see what I can figure out.

**Comment by wleibrook** [comment]
I think it has me as a contributor only for some reason. I created a Github account 10 days ago maybe. You sent me a invite a week ago. I don't know if maybe there arte two difffent logins goin on here.

**Comment by wleibrook** [comment]
![colaborator](https://github.com/recoverysource-sites/hamilton/assets/163310736/2d1b2a67-b8e9-49fc-99b5-0a92d359d510)
I don't know why its not letting me edit. I can edit from my mobile device. And I edited the files Sunday on this login on the pc. For some reason I think I've lost Administrator privlages.

**Comment by wleibrook** [comment]
The only thing that I can think is that I was logged in through the invite that you sent me and perhaps because that expired after 7 days I can no longer edit.  I have an account with GitHub under wleibrook@gmail.com but for some reason when I log in that way I don't have administrator right.

**Comment by wleibrook** [comment]
![deploy failure](https://github.com/recoverysource-sites/hamilton/assets/163310736/20192ac3-40a3-4af3-8487-f24a89c1a2fa)
I tried to do a simple update to test the edit and this is the result.

**Comment by MTecknology** [comment]
The initial issue you reported turned out to be a misunderstanding of the github interface.
The additional bugs you reported should now be resolved.

I'm going to close this, but feel free to let me know if you run into other issues.
