### ISSUE TITLE
Update Meeting Info Failed

### ISSUE THREAD

**Issue by wleibrook** [recoverysource-sites/hamilton#2]
I made changes to the meeting.yaml file and it failed to update. Not sure what I broke? I just seperated out all the metings at the 12 (club)  renamed the Club and gave each meeting its own name

**Comment by MTecknology** [comment]
As discussed, we will continue this type of support request via discord.
This particular issue was caused by invalid spacing and duplicate group "shortnames". It has now been resolved.
